# -*- coding: utf-8 -*-
"""assignment-topsis for pre trained models

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12NKooMjBUHZdp5eemBAC6szNNJLcVuuN
"""

import time
from transformers import pipeline
from sklearn.metrics import accuracy_score, f1_score
import torch # Import torch to check for GPU availability

# Initialize an empty list named model_metrics_list
model_metrics_list = []

# Define device for GPU if available, else CPU
device = 0 if torch.cuda.is_available() else -1
print(f"Using device: {'cuda' if device == 0 else 'cpu'}")

# Iterate through each model_name in the model_names list
for model_name in model_names:
    current_model_metrics = {}
    current_model_metrics['Model Name'] = model_name

    print(f"\nEvaluating model: {model_name}")

    # Instantiate a text-classification pipeline, ensuring GPU usage if available
    # Using return_all_scores=False for efficiency, as we only need the top prediction
    classifier = pipeline('text-classification', model=model_name, device=device, return_all_scores=False)

    # Calculate the total number of parameters and model size
    # Assuming float32 (4 bytes per parameter) for model size calculation
    model_size_bytes = sum(p.numel() for p in classifier.model.parameters()) * 4
    current_model_metrics['Model Size (MB)'] = model_size_bytes / (1024 * 1024)

    # Explicitly convert the 'text' column to a list of pure Python strings
    texts = list(subset_dataset['text'])

    # Record the start_time
    start_time = time.perf_counter()

    # Perform inference
    # The pipeline handles batching internally, so passing the full list is fine.
    predictions = classifier(texts)

    # Record the end_time
    end_time = time.perf_counter()

    # Calculate the inference_time_per_sample
    inference_time_per_sample = (end_time - start_time) / len(subset_dataset)
    current_model_metrics['Inference Time Per Sample (s)'] = inference_time_per_sample

    # Process predictions: extract predicted labels. The pipeline usually returns dictionaries.
    # The `label` key will contain 'LABEL_X' where X is the class index.
    # We need to extract the integer X.
    predicted_labels = [int(p['label'].split('_')[-1]) for p in predictions]

    # Explicitly convert the 'label' column to a list of integers
    true_labels = list(subset_dataset['label'])

    # Calculate Accuracy
    accuracy = accuracy_score(true_labels, predicted_labels)
    current_model_metrics['Accuracy'] = accuracy

    # Calculate Macro F1 Score
    # Ensure labels are explicitly passed if not all labels are present in the predictions/truths
    # (though with 300 samples and 4 classes, it's likely all are present)
    macro_f1 = f1_score(true_labels, predicted_labels, average='macro', labels=list(range(num_labels))) # num_labels is 4 for AG News
    current_model_metrics['Macro F1 Score'] = macro_f1

    # Retrieve computational cost from the predefined map
    current_model_metrics['Computational Cost'] = computational_cost_map.get(model_name, 0)

    # Append the current_model_metrics dictionary to model_metrics_list
    model_metrics_list.append(current_model_metrics)

# Print the model_metrics_list for verification
print("\nCollected Model Metrics:")
for metrics in model_metrics_list:
    print(metrics)
    import time
from transformers import pipeline
from sklearn.metrics import accuracy_score, f1_score
import torch

# Initialize an empty list named model_metrics_list
model_metrics_list = []

# Determine the available device (GPU or CPU)
device = 0 if torch.cuda.is_available() else -1
print(f"Using device: {'GPU' if device == 0 else 'CPU'}")

# Iterate through each model_name in the model_names list
for model_name in model_names:
    current_model_metrics = {}
    current_model_metrics['Model Name'] = model_name

    print(f"\nEvaluating model: {model_name}")

    # Instantiate a text-classification pipeline, ensuring GPU usage if available
    # and setting return_all_scores=False (which is the default for single-label classification)
    classifier = pipeline('text-classification', model=model_name, device=device, return_all_scores=False)

    # Calculate the total number of parameters and model size
    # Assuming float32 (4 bytes per parameter) for model size calculation
    model_size_bytes = sum(p.numel() for p in classifier.model.parameters()) * 4
    current_model_metrics['Model Size (MB)'] = model_size_bytes / (1024 * 1024)

    # Explicitly convert the 'text' column for inference to a list of strings
    texts = list(subset_dataset['text'])

    # Record the start_time
    start_time = time.perf_counter()

    # Perform inference
    predictions = classifier(texts)

    # Record the end_time
    end_time = time.perf_counter()

    # Calculate the inference_time_per_sample
    inference_time_per_sample = (end_time - start_time) / len(subset_dataset)
    current_model_metrics['Inference Time Per Sample (s)'] = inference_time_per_sample

    # Process predictions: extract predicted labels
    # Predictions can be a list of dicts, each with a 'label' key like 'LABEL_X'
    # We need to extract the integer X.
    predicted_labels = [int(p['label'].split('_')[-1]) for p in predictions]

    # Explicitly convert the true labels to a list of integers
    true_labels = list(subset_dataset['label'])

    # Calculate Accuracy
    accuracy = accuracy_score(true_labels, predicted_labels)
    current_model_metrics['Accuracy'] = accuracy

    # Calculate Macro F1 Score
    # num_labels should be available from the previous context, typically 4 for AG News
    macro_f1 = f1_score(true_labels, predicted_labels, average='macro', labels=list(range(num_labels)))
    current_model_metrics['Macro F1 Score'] = macro_f1

    # Retrieve computational cost
    current_model_metrics['Computational Cost'] = computational_cost_map.get(model_name, 0)

    # Append the current_model_metrics dictionary to model_metrics_list
    model_metrics_list.append(current_model_metrics)

# Print the model_metrics_list
print("\nCollected Model Metrics:")
for metrics in model_metrics_list:
    print(metrics)
    import time
from transformers import pipeline, AutoModelForSequenceClassification, AutoTokenizer, AutoConfig
from sklearn.metrics import accuracy_score, f1_score
import torch

# Initialize an empty list named model_metrics_list
model_metrics_list = []

# Determine the available device (GPU or CPU)
device = 0 if torch.cuda.is_available() else -1
print(f"Using device: {'GPU' if device == 0 else 'CPU'}")

# Iterate through each model_name in the model_names list
for model_name in model_names:
    current_model_metrics = {}
    current_model_metrics['Model Name'] = model_name

    print(f"\nEvaluating model: {model_name}")

    # Explicitly load config, tokenizer, and model to ensure num_labels is passed
    # This helps ensure the classification head is correctly initialized, even if randomly
    config = AutoConfig.from_pretrained(model_name, num_labels=num_labels)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name, config=config)

    # Instantiate a text-classification pipeline, ensuring GPU usage if available
    # and setting return_all_scores=False (which is the default for single-label classification)
    classifier = pipeline(
        'text-classification',
        model=model,
        tokenizer=tokenizer,
        device=device,
        return_all_scores=False
    )

    # Calculate the total number of parameters and model size
    # Assuming float32 (4 bytes per parameter) for model size calculation
    model_size_bytes = sum(p.numel() for p in classifier.model.parameters()) * 4
    current_model_metrics['Model Size (MB)'] = model_size_bytes / (1024 * 1024)

    # Explicitly convert the 'text' column for inference to a list of strings
    texts = list(subset_dataset['text'])

    # Record the start_time
    start_time = time.perf_counter()

    # Perform inference
    predictions = classifier(texts)

    # Record the end_time
    end_time = time.perf_counter()

    # Calculate the inference_time_per_sample
    inference_time_per_sample = (end_time - start_time) / len(subset_dataset)
    current_model_metrics['Inference Time Per Sample (s)'] = inference_time_per_sample

    # Process predictions: extract predicted labels
    # Predictions can be a list of dicts, each with a 'label' key like 'LABEL_X'
    # We need to extract the integer X.
    predicted_labels = [int(p['label'].split('_')[-1]) for p in predictions]

    # Explicitly convert the true labels to a list of integers
    true_labels = list(subset_dataset['label'])

    # Calculate Accuracy
    accuracy = accuracy_score(true_labels, predicted_labels)
    current_model_metrics['Accuracy'] = accuracy

    # Calculate Macro F1 Score
    # num_labels should be available from the previous context, typically 4 for AG News
    macro_f1 = f1_score(true_labels, predicted_labels, average='macro', labels=list(range(num_labels)))
    current_model_metrics['Macro F1 Score'] = macro_f1

    # Retrieve computational cost
    current_model_metrics['Computational Cost'] = computational_cost_map.get(model_name, 0)

    # Append the current_model_metrics dictionary to model_metrics_list
    model_metrics_list.append(current_model_metrics)

# Print the model_metrics_list
print("\nCollected Model Metrics:")
for metrics in model_metrics_list:
    print(metrics)
    import time
from transformers import pipeline, AutoModelForSequenceClassification, AutoTokenizer, AutoConfig
from sklearn.metrics import accuracy_score, f1_score
import torch

# Initialize an empty list named model_metrics_list
model_metrics_list = []

# Determine the available device (GPU or CPU)
device = 0 if torch.cuda.is_available() else -1
print(f"Using device: {'GPU' if device == 0 else 'CPU'}")

# Iterate through each model_name in the model_names list
for model_name in model_names:
    current_model_metrics = {}
    current_model_metrics['Model Name'] = model_name

    print(f"\nEvaluating model: {model_name}")

    # Explicitly load config, tokenizer, and model to ensure num_labels is passed
    # This helps ensure the classification head is correctly initialized, even if randomly
    config = AutoConfig.from_pretrained(model_name, num_labels=num_labels)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModelForSequenceClassification.from_pretrained(model_name, config=config)

    # Instantiate a text-classification pipeline, ensuring GPU usage if available
    # and setting return_all_scores=False (which is the default for single-label classification)
    classifier = pipeline(
        'text-classification',
        model=model,
        tokenizer=tokenizer,
        device=device,
        return_all_scores=False
    )

    # Calculate the total number of parameters and model size
    # Assuming float32 (4 bytes per parameter) for model size calculation
    model_size_bytes = sum(p.numel() for p in classifier.model.parameters()) * 4
    current_model_metrics['Model Size (MB)'] = model_size_bytes / (1024 * 1024)

    # Explicitly convert the 'text' column for inference to a list of strings
    texts = list(subset_dataset['text'])

    # Record the start_time
    start_time = time.perf_counter()

    # Perform inference
    predictions = classifier(texts)

    # Record the end_time
    end_time = time.perf_counter()

    # Calculate the inference_time_per_sample
    inference_time_per_sample = (end_time - start_time) / len(subset_dataset)
    current_model_metrics['Inference Time Per Sample (s)'] = inference_time_per_sample

    # Process predictions: extract predicted labels
    # Predictions can be a list of dicts, each with a 'label' key like 'LABEL_X'
    # We need to extract the integer X.
    predicted_labels = [int(p['label'].split('_')[-1]) for p in predictions]

    # Explicitly convert the true labels to a list of integers
    true_labels = list(subset_dataset['label'])

    # Calculate Accuracy
    accuracy = accuracy_score(true_labels, predicted_labels)
    current_model_metrics['Accuracy'] = accuracy

    # Calculate Macro F1 Score
    # num_labels should be available from the previous context, typically 4 for AG News
    macro_f1 = f1_score(true_labels, predicted_labels, average='macro', labels=list(range(num_labels)))
    current_model_metrics['Macro F1 Score'] = macro_f1

    # Retrieve computational cost
    current_model_metrics['Computational Cost'] = computational_cost_map.get(model_name, 0)

    # Append the current_model_metrics dictionary to model_metrics_list
    model_metrics_list.append(current_model_metrics)

# Print the model_metrics_list
print("\nCollected Model Metrics:")
for metrics in model_metrics_list:
    print(metrics)
    import pandas as pd

# Convert the list of dictionaries to a Pandas DataFrame
metrics_df = pd.DataFrame(model_metrics_list)

# Display the DataFrame for review
print("\nModel Performance Metrics:")
display(metrics_df)
import pandas as pd

# 1. Create a copy of the metrics_df DataFrame and name it decision_matrix
decision_matrix = metrics_df.copy()

# 2. Define a dictionary named criteria_type that specifies whether each metric is a 'benefit' or 'cost'
criteria_type = {
    'Accuracy': 'benefit',
    'Macro F1 Score': 'benefit',
    'Inference Time Per Sample (s)': 'cost',
    'Model Size (MB)': 'cost',
    'Computational Cost': 'cost'
}

# 3. Verify the structure and content of your decision_matrix and criteria_type
print("\nDecision Matrix:")
display(decision_matrix)

print("\nCriteria Type:")
print(criteria_type)
import numpy as np

# 1. Define weights for each criterion (example: equal weights)
weights = {
    'Accuracy': 0.2,
    'Macro F1 Score': 0.2,
    'Inference Time Per Sample (s)': 0.2,
    'Model Size (MB)': 0.2,
    'Computational Cost': 0.2
}

# Ensure weights sum to 1 (optional check)
if abs(sum(weights.values()) - 1.0) > 1e-9:
    print("Warning: Weights do not sum to 1. Normalizing weights...")
    total_weight = sum(weights.values())
    weights = {k: v / total_weight for k, v in weights.items()}

# 2. Create a copy of the decision_matrix and remove 'Model Name' column
topsis_matrix = decision_matrix.drop(columns=['Model Name']).copy()

# 3. Normalize the topsis_matrix using vector normalization
# For each column (criterion), divide each value by the square root of the sum of the squares of all values in that column.
normalized_matrix = topsis_matrix.copy()
for col in topsis_matrix.columns:
    normalized_matrix[col] = topsis_matrix[col] / np.sqrt(np.sum(topsis_matrix[col]**2))

print("Weights:")
print(weights)
print("\nTOPSIS Matrix (numerical columns only):")
display(topsis_matrix)
print("\nNormalized Matrix:")
display(normalized_matrix)
import pandas as pd

# 4. Apply the defined weights to the normalized_matrix
weighted_normalized_matrix = normalized_matrix.copy()
for col, weight in weights.items():
    if col in weighted_normalized_matrix.columns:
        weighted_normalized_matrix[col] = normalized_matrix[col] * weight

print("\nWeighted Normalized Matrix:")
display(weighted_normalized_matrix)
import pandas as pd

# 5. Determine the Positive Ideal Solution (PIS) and Negative Ideal Solution (NIS)
pis = pd.Series(index=weighted_normalized_matrix.columns, dtype=float)
nis = pd.Series(index=weighted_normalized_matrix.columns, dtype=float)

for col in weighted_normalized_matrix.columns:
    if col in criteria_type:
        if criteria_type[col] == 'benefit':
            pis[col] = weighted_normalized_matrix[col].max()
            nis[col] = weighted_normalized_matrix[col].min()
        elif criteria_type[col] == 'cost':
            pis[col] = weighted_normalized_matrix[col].min()
            nis[col] = weighted_normalized_matrix[col].max()
    else:
        # Handle cases where a column might not be in criteria_type if necessary
        # For this specific task, all columns in weighted_normalized_matrix are in criteria_type
        pass

print("\nPositive Ideal Solution (PIS):")
print(pis)
print("\nNegative Ideal Solution (NIS):")
print(nis)
import numpy as np

# 6. Calculate the separation of each model from the PIS (separation_from_pis) and NIS (separation_from_nis)
# This is done by computing the Euclidean distance between each row of the weighted_normalized_matrix
# and the pis/nis vectors.

# For PIS
separation_from_pis = np.sqrt(np.sum((weighted_normalized_matrix - pis)**2, axis=1))

# For NIS
separation_from_nis = np.sqrt(np.sum((weighted_normalized_matrix - nis)**2, axis=1))

print("\nSeparation from PIS:")
print(separation_from_pis)
print("\nSeparation from NIS:")
print(separation_from_nis)
import pandas as pd

# 7. Calculate the TOPSIS score (Closeness Coefficient) for each model
topsis_score = separation_from_nis / (separation_from_pis + separation_from_nis)

# Add the TOPSIS score to the decision_matrix
decision_matrix['TOPSIS Score'] = topsis_score

print("\nDecision Matrix with TOPSIS Scores:")
display(decision_matrix)
import pandas as pd

# 8. Rank the models based on their 'TOPSIS Score' in descending order
ranked_models = decision_matrix[['Model Name', 'TOPSIS Score']].sort_values(by='TOPSIS Score', ascending=False).reset_index(drop=True)

# 9. Display the ranked_models DataFrame
print("Ranked Models:")
display(ranked_models)
metrics_df.to_csv('model_classification_metrics.csv', index=False)
print("Saved 'model_classification_metrics.csv'")
ranked_models.to_csv('topsis_classification_ranking.csv', index=False)
print("Saved 'topsis_classification_ranking.csv'")
import matplotlib.pyplot as plt
import seaborn as sns

# 2. Set a suitable figure size and style for the plots
sns.set_style("whitegrid")

# List of metrics to plot from metrics_df
metrics_to_plot_df = [
    {'column': 'Accuracy', 'title': 'Model Accuracy Comparison', 'ylabel': 'Accuracy', 'filename': 'accuracy_comparison.png'},
    {'column': 'Macro F1 Score', 'title': 'Model Macro F1 Score Comparison', 'ylabel': 'Macro F1 Score', 'filename': 'macro_f1_comparison.png'},
    {'column': 'Inference Time Per Sample (s)', 'title': 'Model Inference Time Comparison', 'ylabel': 'Inference Time Per Sample (s)', 'filename': 'inference_time_comparison.png'}
]

for metric_info in metrics_to_plot_df:
    plt.figure(figsize=(10, 6)) # Set figure size for each plot
    sns.barplot(x='Model Name', y=metric_info['column'], data=metrics_df, palette='viridis')
    plt.title(metric_info['title'], fontsize=16)
    plt.xlabel('Model Name', fontsize=12)
    plt.ylabel(metric_info['ylabel'], fontsize=12)
    plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for better readability
    plt.tight_layout() # Adjust layout to prevent labels from overlapping
    plt.savefig(metric_info['filename']) # Save the plot
    plt.show() # Display the plot
    plt.close() # Close the plot to free memory

# Plotting TOPSIS Score from ranked_models DataFrame
plt.figure(figsize=(10, 6))
sns.barplot(x='Model Name', y='TOPSIS Score', data=ranked_models, palette='magma')
plt.title('TOPSIS Score Ranking', fontsize=16)
plt.xlabel('Model Name', fontsize=12)
plt.ylabel('TOPSIS Score', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('topsis_ranking.png')
plt.show()
plt.close()

print("Generated and saved comparison graphs for Accuracy, Macro F1 Score, Inference Time Per Sample, and TOPSIS Scores.")
import matplotlib.pyplot as plt
import seaborn as sns

# 2. Set a suitable figure size and style for the plots
sns.set_style("whitegrid")

# List of metrics to plot from metrics_df
metrics_to_plot_df = [
    {'column': 'Accuracy', 'title': 'Model Accuracy Comparison', 'ylabel': 'Accuracy', 'filename': 'accuracy_comparison.png'},
    {'column': 'Macro F1 Score', 'title': 'Model Macro F1 Score Comparison', 'ylabel': 'Macro F1 Score', 'filename': 'macro_f1_comparison.png'},
    {'column': 'Inference Time Per Sample (s)', 'title': 'Model Inference Time Comparison', 'ylabel': 'Inference Time Per Sample (s)', 'filename': 'inference_time_comparison.png'}
]

for metric_info in metrics_to_plot_df:
    plt.figure(figsize=(10, 6)) # Set figure size for each plot
    sns.barplot(x='Model Name', y=metric_info['column'], data=metrics_df, palette='viridis', hue='Model Name', legend=False)
    plt.title(metric_info['title'], fontsize=16)
    plt.xlabel('Model Name', fontsize=12)
    plt.ylabel(metric_info['ylabel'], fontsize=12)
    plt.xticks(rotation=45, ha='right') # Rotate x-axis labels for better readability
    plt.tight_layout() # Adjust layout to prevent labels from overlapping
    plt.savefig(metric_info['filename']) # Save the plot
    plt.show() # Display the plot
    plt.close() # Close the plot to free memory

# Plotting TOPSIS Score from ranked_models DataFrame
plt.figure(figsize=(10, 6))
sns.barplot(x='Model Name', y='TOPSIS Score', data=ranked_models, palette='magma', hue='Model Name', legend=False)
plt.title('TOPSIS Score Ranking', fontsize=16)
plt.xlabel('Model Name', fontsize=12)
plt.ylabel('TOPSIS Score', fontsize=12)
plt.xticks(rotation=45, ha='right')
plt.tight_layout()
plt.savefig('topsis_ranking.png')
plt.show()
plt.close()

print("Generated and saved comparison graphs for Accuracy, Macro F1 Score, Inference Time Per Sample, and TOPSIS Scores.")